nodeLinker: node-modules

packageExtensions:
    '@expo/prebuild-config@6.2.6':
        dependencies:
            'expo-modules-autolinking': '>=0.8.1'
    '@react-native/virtualized-lists@0.72.8':
        dependencies:
            'react-native': '*'
    'react-native@0.72.6':
        dependencies:
            react: 18.2.0
    'react-shallow-renderer@16.15.0':
        dependencies:
            react: ^16.0.0 || ^17.0.0 || ^18.0.0
    'use-sync-external-store@1.2.0':
        dependencies:
            react: ^16.8.0 || ^17.0.0 || ^18.0.0
    '@babel/plugin-syntax-flow@7.22.5':
        dependencies:
            '@babel/core': ^7.0.0
    '@babel/helper-create-class-features-plugin@7.22.15':
        dependencies:
            '@babel/core': ^7.0.0
    '@babel/helper-replace-supers@7.22.20':
        dependencies:
            '@babel/core': ^7.0.0
    '@babel/plugin-proposal-decorators@7.23.2':
        dependencies:
            '@babel/core': ^7.0.0
    '@babel/plugin-syntax-decorators@7.22.10':
        dependencies:
            '@babel/core': ^7.0.0
    '@babel/plugin-proposal-export-namespace-from@7.18.9':
        dependencies:
            '@babel/core': '^7.0.0-0'
    '@babel/plugin-proposal-object-rest-spread@7.20.7':
        dependencies:
            '@babel/core': '^7.0.0-0'
    '@babel/plugin-syntax-object-rest-spread@7.8.3':
        dependencies:
            '@babel/core': '^7.0.0-0'
    '@babel/plugin-transform-parameters@7.22.15':
        dependencies:
            '@babel/core': '^7.0.0-0'
    '@babel/plugin-syntax-jsx@7.22.5':
        dependencies:
            '@babel/core': '^7.0.0-0'
    '@babel/plugin-transform-react-jsx@7.22.15':
        dependencies:
            '@babel/core': '^7.0.0-0'
    '@babel/preset-env@^7.1.6':
        dependencies:
            '@babel/core': '^7.0.0-0 || ^8.0.0'
    'expo-constants@14.4.2':
        dependencies:
            'expo': '*'
    'expo-file-system@15.4.4':
        dependencies:
            'expo': '*'
    'eslint-plugin-ft-flow@3.0.1':
        dependencies:
            'hermes-eslint': '^0.15.0 || ^0.16.0'
    '@react-native/codegen@0.72.7':
        dependencies:
            '@babel/preset-env': ^7.1.6
    'jscodeshift@0.14.0':
        dependencies:
            '@babel/preset-env': ^7.1.6
    '@react-native/eslint-config@0.72.2':
        dependencies:
            prettier: '>=2'
    'eslint-plugin-prettier@4.2.1':
        dependencies:
            prettier: '>=2.0.0'
    'react-query-native-devtools@4.0.0':
        dependencies:
            'react-native-flipper': 0.182.0
            'react-query': ^3.34.6
    'react-query@3.39.3':
        dependencies:
            'react': ^16.8.0 || ^17.0.0 || ^18.0.0
    'react-native-reanimated@3.5.4':
        dependencies:
            '@babel/plugin-proposal-nullish-coalescing-operator': '^7.0.0-0'
            '@babel/plugin-proposal-optional-chaining': '^7.0.0-0'
            '@babel/plugin-transform-arrow-functions': '^7.0.0-0'
            '@babel/plugin-transform-shorthand-properties': '^7.0.0-0'
            '@babel/plugin-transform-template-literals': '^7.0.0-0'

yarnPath: .yarn/releases/yarn-3.6.0.cjs
