npmScopes:
    'reptalieregion':
        npmAlwaysAuth: true
        npmAuthToken: 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
        npmRegistryServer: 'https://npm.pkg.github.com'

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.0.cjs
