# .circleci/config.yml
version: 2.1

orbs:
    ruby: circleci/ruby@2.1.1
    macos: circleci/macos@2.4.1

jobs:
    deploy-ios:
        macos:
            xcode: 14.2.0
        steps:
            - checkout
            - macos/switch-ruby:
                  version: '2.7'
            - ruby/install-deps:
                  key: gems-ios
                  app-dir: apps/crawl

            - restore_cache:
                  keys:
                      - yarn-cache-{{ checksum "yarn.lock" }}
            - run:
                  name: yarn install
                  command: yarn install
            - save_cache:
                  key: yarn-cache-{{ checksum "yarn.lock" }}
                  paths:
                      - .yarn/cache

            - restore_cache:
                  keys:
                      - bundle-cache-{{ checksum "apps/crawl/Gemfile.lock" }}
            - run:
                  name: bundle install
                  working_directory: apps/crawl
                  command: bundle install
            - save_cache:
                  key: yarn-cache-{{ checksum "apps/crawl/Gemfile.lock" }}
                  paths:
                      - apps/crawl/vendor/bundle

            - restore_cache:
                  keys:
                      - pod-cache-{{ checksum "apps/crawl/ios/Podfile.lock" }}
            - run:
                  name: pod install
                  working_directory: apps/crawl/ios
                  command: pod install
            - save_cache:
                  key: pod-cache-{{ checksum "apps/crawl/ios/Podfile.lock" }}
                  paths:
                      - apps/crawl/ios/Pods

            - run:
                  name: Fastlane
                  command: yarn deploy:dev 1.1.23

workflows:
    deploy-app:
        jobs:
            - deploy-ios
