# .circleci/config.yml
version: 2.1

orbs:
    ruby: circleci/ruby@2.1.1
    macos: circleci/macos@2

jobs:
    deploy-ios:
        macos:
            xcode: 15.2.0
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - gems-ios-{{ checksum "apps/crawl/Gemfile.lock" }}
            - run:
                  name: Set Ruby Version
                  command: rbenv install 2.7.6
            - save_cache:
                  key: gems-ios-{{ checksum "apps/crawl/Gemfile.lock" }}
                  paths:
                      - apps/crawl/vendor/bundle
            - ruby/install-deps:
                  key: gems-ios
                  app-dir: apps/crawl

            - restore_cache:
                  keys:
                      - yarn-cache-{{ checksum "yarn.lock" }}
            - run:
                  name: yarn install
                  command: yarn install
            - save_cache:
                  key: yarn-cache-{{ checksum "yarn.lock" }}
                  paths:
                      - .yarn/cache
            - run:
                  name: Fastlane
                  command: yarn deploy:dev 1.1.23

workflows:
    deploy-app:
        jobs:
            - deploy-ios
