# .circleci/config.yml
version: 2.1
jobs:
    build-and-test:
        macos:
            xcode: 14.2.0
        steps:
            # ...
            - run: bundle exec fastlane test

    adhoc:
        macos:
            xcode: 14.2.0
        steps:
            # ...
            - run: bundle exec fastlane adhoc

workflows:
    build-test-adhoc:
        jobs:
            - build-and-test
            - adhoc:
                  filters:
                      branches:
                          only: development
                  requires:
                      - build-and-test
