version: 2.1
jobs:
    react-native-test:
        docker:
            - image: cimg/node:18.8
        steps:
            - checkout
            - restore_cache:
                  key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
            - restore_cache:
                  key: node-v1-{{ checksum "package.json" }}-{{ arch }}
            - run: yarn install
            - run: yarn test
            - run: yarn tsc
            - save_cache:
                  key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
                  paths:
                      - ~/.cache/yarn
            - save_cache:
                  key: node-v1-{{ checksum "package.json" }}-{{ arch }}
                  paths:
                      - node_modules

    macos-build-and-deploy:
        macos:
            xcode: 14.2.0
        environment:
            FL_OUTPUT_DIR: output
            FASTLANE_LANE: beta
        steps:
            - checkout
            - restore_cache:
                  key: dependency-cache-{{ checksum "yarn.lock" }}
            - run:
                  name: Install Dependencies
                  command: npm install
            - run: |
                  cd ./apps/crawl/ios
                  bundle install
                  bundle exec fastlane $FASTLANE_LANE version:1.1.23
            - store_artifacts:
                  path: output
            - store_test_results:
                  path: output/scan

workflows:
    build-test-testflight:
        jobs:
            - react-native-test
            - macos-build-and-deploy
