# .circleci/config.yml
version: 2.1

orbs:
    ruby: circleci/ruby@2.1.1
    macos: circleci/macos@2.4.1

jobs:
    deploy-ios:
        macos:
            xcode: 14.2.0
        steps:
            - checkout
            - macos/switch-ruby:
                  version: '2.7.6p219'
            - ruby/install-deps:
                  key: gems-ios
                  app-dir: ./apps/crawl
            - run:
                  name: yarn install
                  command: yarn install
            - run:
                  name: Install pods
                  working_directory: ~/apps/crawl/ios
                  command: |
                      bundle install
                      bundle exec pod install
            - run:
                  name: Fastlane
                  command: yarn deploy:dev 1.1.23

workflows:
    deploy-app:
        jobs:
            - deploy-ios
