# .circleci/config.yml
version: 2.1

jobs:
    yarn-install:
        docker:
            - image: cimg/node:18.19.0
        steps:
            - checkout
            - run:
                  name: Install Node.js and Yarn
                  command: |
                      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
                      export NVM_DIR="$HOME/.nvm"
                      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  
                      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  
                      nvm install --lts
                      npm install -g yarn@3.6.0
            - run:
                  name: yarn install
                  command: |
                      yarn install
    build-and-test:
        macos:
            xcode: 14.2.0
        environment:
            FL_OUTPUT_DIR: output
        steps:
            - run: ls
            - run: cd apps/crawl
            - run:
                  name: bundle install
                  command: bundle install
            - run:
                  name: Fastlane
                  command: cd ios && bundle exec fastlane development 1.1.23
            - store_artifacts:
                  path: output

workflows:
    build-test-adhoc:
        jobs:
            - yarn-install
            - build-and-test:
                  requires:
                      - yarn-install
