version: 2.1
jobs:
    macos-build-and-deploy:
        macos:
            xcode: 15.2.0
        environment:
            FL_OUTPUT_DIR: output
        steps:
            - checkout
            - ruby/install-deps
            - working_directory: ./apps/crawl
            - restore_cache:
                  key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
            - restore_cache:
                  key: node-v1-{{ checksum "package.json" }}-{{ arch }}
            - run: yarn install
            - save_cache:
                  key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
                  paths:
                      - ~/yarn/cache
            - save_cache:
                  key: node-v1-{{ checksum "package.json" }}-{{ arch }}
                  paths:
                      - ~/node_modules
            - restore_cache:
                  key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}
            - restore_cache:
                  key: pods-v1-{{ checksum "ios/Podfile.lock" }}-{{ arch }}
            - run:
                  command: pod install
                  working_directory: ios
            - run:
                  command: bundle install
                  working_directory: ios
            - save_cache:
                  key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}
                  paths:
                      - vendor/bundle
            - save_cache:
                  key: pods-v1-{{ checksum "ios/Podfile.lock" }}-{{ arch }}
                  paths:
                      - ios/Pods
            - run:
                  name: Fastlane deploy TestFlight
                  command: yarn deploy:dev 1.1.23
            - store_artifacts:
                  path: output
            - store_test_results:
                  path: output/scan

workflows:
    build-test-testflight:
        jobs:
            - macos-build-and-deploy:
                  filters:
                      tags:
                          only: /crawl-*-ios/
