version: 2.1
jobs:
    build-and-test:
        macos:
            xcode: 15.2.0
        environment:
            FASTLANE_LANE: beta
        steps:
            - run: |
                  cd ./apps/crawl/ios
                  bundle install
                  bundle exec fastlane $FASTLANE_LANE version:1.1.23

workflows:
    build-test-testflight:
        jobs:
            - build-and-test:
                  filters:
                      tags:
                          only: crawl/*-ios
