# .circleci/config.yml
version: 2.1

orbs:
    node: circleci/node@5.2.0

jobs:
    yarn-install:
        executor:
            name: node/default
            tag: '18.18'
        steps:
            - checkout
            - node/install-packages:
                  pkg-manager: yarn-berry
            - run:
                  name: yarn install
                  command: |
                      yarn install
    fastlane-build:
        macos:
            xcode: 14.2.0
        environment:
            FL_OUTPUT_DIR: output
        steps:
            - run: ls
            - run: cd apps/crawl
            - run:
                  name: bundle install
                  command: bundle install
            - run:
                  name: Fastlane
                  command: cd ios && bundle exec fastlane development 1.1.23
            - store_artifacts:
                  path: output

workflows:
    build:
        jobs:
            - yarn-install
            - fastlane-build:
                  requires:
                      - yarn-install
