version: 2.1
jobs:
    build-and-test:
        macos:
            xcode: 15.2.0
        environment:
            FL_OUTPUT_DIR: output
            FASTLANE_LANE: beta
        steps:
            - checkout
            - run: |
                  ls
                  cd ./apps/crawl/ios
                  bundle install
                  bundle exec fastlane $FASTLANE_LANE version:1.1.23
            - store_artifacts:
                  path: output
            - store_test_results:
                  path: output/scan

workflows:
    build-test-testflight:
        jobs:
            - build-and-test:
                  filters: &tagged
                      tags:
                          only: /crawl/*-ios/
