# .circleci/config.yml
version: 2.1
jobs:
    development:
        macos:
            xcode: 14.2.0
        steps:
            - run: bundle exec fastlane development 1.1.23

workflows:
    build-test-development:
        jobs:
            - development:
                  filters:
                      branches:
                          only: development
