# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new verison to the Google Play - DEV"
  lane :dev do
    increment_version_code(
      gradle_file_path: "./app/build.gradle",
    )
    gradle(task: "clean bundleRelease")
    upload_to_play_store(
      package_name: 'com.crawl.dev',
      aab: './app/build/outputs/bundle/developmentRelease/app-development-release.aab',
      track: 'internal',
      release_status: 'draft'
    )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :prod do
    increment_version_code(
      gradle_file_path: "./app/build.gradle",
    )
    gradle(task: "clean bundleRelease")
    upload_to_play_store(
      package_name: 'com.crawl',
      aab: './app/build/outputs/bundle/productionRelease/app-production-release.aab',
      track: 'internal',
      release_status: 'draft'
    )
  end
end
