name: Build and Deploy iOS Dev

on:
    push:
        tags:
            - reptile-region/*-ios
jobs:
    testFlight-build:
        name: iOS-testFlight-build
        runs-on: macos-latest
        timeout-minutes: 25
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - name: Install SSH key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.SSH_KEY }}
                  known_hosts: ${{ secrets.KNOWN_HOSTS }}
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Checkout to git repository
              uses: actions/checkout@v4
            - name: Install Dependencies
              run: |
                  yarn install
            - name: Install Fastlane
              run: |
                  cd ./apps/reptile-region
                  yarn set:env:dev
                  cd ./ios
                  bundle install
                  bundle update fastlane
            - name: Build and Upload to TestFlight (Beta)
              run: |
                  cd ./apps/reptile-region/ios
                  fastlane env
                  bundle exec fastlane beta:1.0.2
                  env:
                    MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
                    MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
                    MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
                    GIT_URL: ${{ secrets.GIT_URL }}
                    FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
